service: auth-sample-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: handler.endpoint
    events: 
      - http: 
          path: ping
          method: GET
          cors: true
      